//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.23 at 04:28:17 PM ICT 
//


package vlu.architect.team7.vexere.service.soap;

import vlu.architect.team7.vexere.service.Model.BusTrain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusTrainDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusTrainDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licensePlate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="departureTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusTrainDTO", propOrder = {
    "licensePlate",
    "departureTime",
    "startPlace",
    "targetPlace"
})
public class BusTrainDTO {

    @XmlElement(required = true)
    protected String licensePlate;
    @XmlElement(required = true)
    protected String departureTime;
    @XmlElement(required = true)
    protected String startPlace;
    @XmlElement(required = true)
    protected String targetPlace;

    /**
     * Gets the value of the licensePlate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicensePlate() {
        return licensePlate;
    }

    /**
     * Sets the value of the licensePlate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicensePlate(String value) {
        this.licensePlate = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureTime(String value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the startPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPlace() {
        return startPlace;
    }

    /**
     * Sets the value of the startPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPlace(String value) {
        this.startPlace = value;
    }

    /**
     * Gets the value of the targetPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetPlace() {
        return targetPlace;
    }

    /**
     * Sets the value of the targetPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetPlace(String value) {
        this.targetPlace = value;
    }

    public static BusTrainDTO from(BusTrain busTrain) {
        BusTrainDTO busTrainDTO = new BusTrainDTO();
        busTrainDTO.licensePlate = busTrain.getLicensePlate();
        busTrainDTO.departureTime = String.format("%s %s", busTrain.getStartDate(), busTrain.getStartTime());
        busTrainDTO.startPlace = busTrain.getStartPlace().getPlaceName();
        busTrainDTO.targetPlace = busTrain.getTargetPlace().getPlaceName();
        return busTrainDTO;
    }

}
