//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.23 at 04:28:17 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://architect.vlu/team7/vexere/service/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vlu.architect.team7.vexere.service.soap;
