//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.17 at 10:51:54 PM ICT 
//


package vlu.architect.team7.def_garage.def_garage_service.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vlu.architect.team7.def_garage.def_garage_service.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vlu.architect.team7.def_garage.def_garage_service.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindAllBusTrainRequest }
     * 
     */
    public FindAllBusTrainRequest createFindAllBusTrainRequest() {
        return new FindAllBusTrainRequest();
    }

    /**
     * Create an instance of {@link FindAllBusTrainResponse }
     * 
     */
    public FindAllBusTrainResponse createFindAllBusTrainResponse() {
        return new FindAllBusTrainResponse();
    }

    /**
     * Create an instance of {@link BusTrainDTO }
     * 
     */
    public BusTrainDTO createBusTrainDTO() {
        return new BusTrainDTO();
    }

}
