//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.17 at 10:51:54 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://architect.vlu/team7/def_garage/def_garage_service/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vlu.architect.team7.def_garage.def_garage_service.soap;
