server:
  port: 8001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: searching-service
          uri: lb://searching-service
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
        - id: futa-caller
          uri: lb://futa-caller
          predicates:
            - Path=/futa/**
          filters:
            - StripPrefix=1
        - id: vexere-caller
          uri: lb://vexere-caller
          predicates:
            - Path=/vexere/**
          filters:
            - StripPrefix=1
        - id: cache
          uri: lb://cache
          predicates:
            - Path=/cache/**
          filters:
            - StripPrefix=1
        - id: min-cost
          uri: lb://minimum-cost-service
          predicates:
            - Path=/min-cost/**
          filters:
            - StripPrefix=1
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

info:
  app:
    name: gateway

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info