
spring:
  application:
    name: vexere-service
  datasource:
    url: jdbc:mariadb://localhost:3306/ArchitectTeam7_Soap
    username: sa
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicity-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

server:
  port: 8202

info:
  app:
    name: futa-service

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8200/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info