//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.06 at 07:33:45 PM ICT 
//


package vlu.architect.team7.partner.vexere.service.soap;

import lombok.Getter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrainItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlaceItemDTO", propOrder = {
    "startPlace",
    "targetPlace"
})
@Getter
public class PlaceItemDTO {

    @XmlElement(required = true)
    protected String startPlace;
    @XmlElement(required = true)
    protected String targetPlace;

    public static PlaceItemDTO create(String startPlace, String targetPlace) {
        PlaceItemDTO itemDTO = new PlaceItemDTO();
        itemDTO.startPlace = startPlace;
        itemDTO.targetPlace = targetPlace;
        return itemDTO;
    }
}
