
spring:
  application:
    name: vexere-caller

server:
  port: 8004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 10000